export const currencies = [
  {
    name: 'US Dollar',
    currencyCode: 'usd',
    countryCode: 'us',
    glyph: '$',
    endGlyph: false,
    searchExtra: 'united states',
  },
  {
    name: 'Euro',
    currencyCode: 'eur',
    countryCode: 'eu',
    glyph: '€',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Japanese Yen',
    currencyCode: 'hpy',
    countryCode: 'jp',
    glyph: '¥',
    endGlyph: false,
    searchExtra: '円',
  },
  {
    name: 'British Pound',
    currencyCode: 'gbp',
    countryCode: 'gb',
    glyph: '£',
    endGlyph: false,
    searchExtra: 'sterling great britain united kingdom uk england',
  },
  {
    name: 'Chinese Yuan',
    currencyCode: 'cny',
    countryCode: 'cn',
    glyph: '¥',
    endGlyph: false,
    searchExtra: 'renminbi 人民币 rénmínbì',
  },
  {
    name: 'Australian Dollar',
    currencyCode: 'aud',
    countryCode: 'au',
    glyph: '$',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Canadian Dollar',
    currencyCode: 'cad',
    countryCode: 'ca',
    glyph: '$',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Swiss Franc',
    currencyCode: 'chf',
    countryCode: 'ch',
    glyph: 'CHF',
    endGlyph: false,
    searchExtra: 'switzerland',
  },
  {
    name: 'Hong Kong Dollar',
    currencyCode: 'hkd',
    countryCode: 'hk',
    glyph: '$',
    endGlyph: false,
    searchExtra: '港元',
  },
  {
    name: 'Singapore Dollar',
    currencyCode: 'sgd',
    countryCode: 'sg',
    glyph: '$',
    endGlyph: false,
    searchExtra: 'sen 分 fēn காசு kācu',
  },
  {
    name: 'Swedish Krona',
    currencyCode: 'sek',
    countryCode: 'se',
    glyph: 'kr',
    endGlyph: true,
    searchExtra: 'sweden svensk sverige',
  },
  {
    name: 'South Korean Won',
    currencyCode: 'krw',
    countryCode: 'kr',
    glyph: '₩',
    endGlyph: false,
    searchExtra: '대한민국 원',
  },
  {
    name: 'Norwegian Krone',
    currencyCode: 'nok',
    countryCode: 'no',
    glyph: 'kr',
    endGlyph: true,
    searchExtra: 'norway norsk norge noreg',
  },
  {
    name: 'New Zealand Dollar',
    currencyCode: 'nzd',
    countryCode: 'nz',
    glyph: '$',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Indian Rupee',
    currencyCode: 'inr',
    countryCode: 'in',
    glyph: '₹',
    endGlyph: false,
    searchExtra:
      '	ভারতীয় টাকা भारतीय रुपया 	ہِندوستٲنؠ رۄپَے भारतीय रुपैयाँ ਭਾਰਤੀ ਰੁਪਿਆ 	भारतीय रुपये 	هندستاني روپيو 	இந்திய ரூபாய் భారత రూపాయి 	ہندوستانی روپیہ',
  },
  {
    name: 'Mexican Peso',
    currencyCode: 'mxn',
    countryCode: 'mx',
    glyph: '$',
    endGlyph: false,
    searchExtra: 'mexico mexicano',
  },
  {
    name: 'New Taiwan Dollar',
    currencyCode: 'twd',
    countryCode: 'tw',
    glyph: 'NT$',
    endGlyph: false,
    searchExtra: '新臺幣',
  },
  {
    name: 'South African Rand',
    currencyCode: 'zar',
    countryCode: 'za',
    glyph: 'R',
    endGlyph: false,
    searchExtra: 'suid afrikaanse iranti rhandi rannda',
  },
  {
    name: 'Brazilian Real',
    currencyCode: 'brl',
    countryCode: 'br',
    glyph: 'R$',
    endGlyph: false,
    searchExtra: 'brasileiro',
  },
  {
    name: 'Danish Krone',
    currencyCode: 'dkk',
    countryCode: 'dk',
    glyph: 'kr',
    endGlyph: true,
    searchExtra: 'denmark dansk donsk króna danskit koruuni',
  },
  {
    name: 'Polish Złoty',
    currencyCode: 'pln',
    countryCode: 'pl',
    glyph: 'zł',
    endGlyph: true,
    searchExtra: 'poland polska polski zloty',
  },
  {
    name: 'Thai Baht',
    currencyCode: 'thb',
    countryCode: 'th',
    glyph: '฿',
    endGlyph: false,
    searchExtra: 'thailand บาทไทย',
  },
  {
    name: 'Israeli New Shekel',
    currencyCode: 'ils',
    countryCode: 'il',
    glyph: '₪',
    endGlyph: false,
    searchExtra:
      'שֶׁקֶל חָדָשׁ sheqel ẖadash شيكل جديد šēkal jadīd sheqel hadash sekal jadid שקל ישראלי sheqel yisreʾeli شيكل إسرائيلي šēkal ʾisrāʾīlī sekal israili',
  },
  {
    name: 'Indonesian Rupiah',
    currencyCode: 'idr',
    countryCode: 'id',
    glyph: 'Rp',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Czech Koruna',
    currencyCode: 'czk',
    countryCode: 'cz',
    glyph: 'Kč',
    endGlyph: true,
    searchExtra: 'koruna česká ceska',
  },
  {
    name: 'UAE Dirham',
    currencyCode: 'aed',
    countryCode: 'ae',
    glyph: 'Dhs',
    endGlyph: false,
    searchExtra: 'united arab emirates درهم إماراتي',
  },
  {
    name: 'Turkish Lira',
    currencyCode: 'try',
    countryCode: 'tr',
    glyph: '₺',
    endGlyph: false,
    searchExtra: 'turkey turkiye türkiye türk lirası',
  },
  {
    name: 'Hungarian Forint',
    currencyCode: 'huf',
    countryCode: 'hu',
    glyph: 'Ft',
    endGlyph: false,
    searchExtra: 'hungary magyar',
  },
  {
    name: 'Chilean Peso',
    currencyCode: 'clp',
    countryCode: 'cl',
    glyph: '$',
    endGlyph: false,
    searchExtra: '',
  },
  {
    name: 'Saudi Riyal',
    currencyCode: 'sar',
    countryCode: 'sa',
    glyph: 'SR',
    endGlyph: false,
    searchExtra: 'saudi arabia ريال سعودي riyāl suʿūdiyy riyal suudiyy',
  },
  {
    name: 'Philippine Peso',
    currencyCode: 'php',
    countryCode: 'ph',
    glyph: '₱',
    endGlyph: false,
    searchExtra: 'piso ng pilipinas',
  },
  {
    name: 'Malaysian Ringgit',
    currencyCode: 'myr',
    countryCode: 'my',
    glyph: 'RM',
    endGlyph: false,
    searchExtra: 'ريڠݢيت مليسيا',
  },
  {
    name: 'Colombian Peso',
    currencyCode: 'cop',
    countryCode: 'co',
    glyph: '$',
    endGlyph: false,
    searchExtra: 'colombiano',
  },
  {
    name: 'Russian Ruble',
    currencyCode: 'rub',
    countryCode: 'ru',
    glyph: '₽',
    endGlyph: true,
    searchExtra: 'рф россия российская федерация российский рубль',
  },
  {
    name: 'Romanian Leu',
    currencyCode: 'ron',
    countryCode: 'ro',
    glyph: 'lei',
    endGlyph: false,
    searchExtra: 'leu românesc românia',
  },
  {
    name: 'Peruvian Sol',
    currencyCode: 'pen',
    countryCode: 'pe',
    glyph: 'S/',
    endGlyph: false,
    searchExtra: 'peruano',
  },
  {
    name: 'Serbian Dinar',
    currencyCode: 'rsd',
    countryCode: 'rs',
    glyph: 'Дин.',
    endGlyph: true,
    searchExtra: 'srpski dinar српски динар',
  },
  {
    name: 'Kazakhstani Tenge',
    currencyCode: 'kzt',
    countryCode: 'kz',
    glyph: '₸',
    endGlyph: false,
    searchExtra: 'қазақстан теңгесі qazaqstan teñgesi казахстанский тенге',
  },
  {
    name: 'Armenian Dram',
    currencyCode: 'amd',
    countryCode: 'am',
    glyph: '֏',
    endGlyph: false,
    searchExtra: 'hayastan Հայաստան Հայկական Դրամ',
  },
  {
    name: 'Georgian Lari',
    currencyCode: 'gel',
    countryCode: 'ge',
    glyph: '₾',
    endGlyph: false,
    searchExtra: 'ქართული ლარი',
  },
]

export const currenciesByCode = Object.fromEntries(
  currencies.map((currency) => [currency.currencyCode, currency]),
)
export const currenciesSelect = currencies.map(({ name, currencyCode }) => ({
  label: `${currencyCode} -- ${name}`,
  value: currencyCode,
}))
export const currencyCountry = Object.fromEntries(
  currencies.map(({ currencyCode, countryCode }) => [
    currencyCode,
    countryCode,
  ]),
)
